name: Fetch Nifty Option Chain

on:
  schedule:
    - cron: '*/5 * * * *'   # Every 5 minutes
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python Script
        run: |
          python fetch_option_chain.py

      - name: Commit JSON
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add option_chain.json

          git diff --cached --quiet || git commit -m "Update Option Chain"

          git push
